### ISSUE TITLE
As a developer, I want to integrate a weather API so that the app can fetch and display current weather data.

### ISSUE THREAD

**Issue by laurelbonal** [Swatzell/better-weather#8]
Task 1: Research and choose a suitable weather API.
Acceptance Criteria: A weather API is selected based on reliability, data accuracy, and cost.
Task 2: Implement API integration to fetch current weather data.
Acceptance Criteria: Weather data is fetched successfully and displayed in the app.
Task 3: Handle errors and edge cases (e.g., API rate limits, network errors).
Acceptance Criteria: Error handling is implemented and the app provides user-friendly error messages.

**Comment by zachwolek** [comment]
Weather data to be gathered from the request 'https://api.openweathermap.org/data/3.0/onecall?lat='+latitude+'&lon='+longitude+'&exclude=minutely&appid=b6c20e33c539bc3bf6a4cd3dcc54e835&units=imperial' (replace latitude and longitude with coordinates)

Cost of the API is one single request
